# Generated by Django 5.1.1 on 2024-09-27 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('conference', 'Conference'), ('fest', 'College Fest'), ('corporate', 'Corporate Event')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('budget', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_guests', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speakers', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.OneToOneField(limit_choices_to={'event_type': 'CONFERENCE'}, on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeFestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fest_name', models.CharField(max_length=255)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.OneToOneField(limit_choices_to={'event_type': 'FEST'}, on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
        migrations.CreateModel(
            name='BirthdayDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bd_person', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('event', models.OneToOneField(limit_choices_to={'event_type': 'BIRTHDAY'}, on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=255)),
                ('groom_name', models.CharField(max_length=255)),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('event', models.OneToOneField(limit_choices_to={'event_type': 'WEDDING'}, on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
    ]
