# Generated by Django 5.1.1 on 2024-09-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organiser',
        ),
    ]
