# Generated by Django 5.1.1 on 2024-09-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_rename_organizer_event_organiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
