# Generated by Django 5.1.1 on 2024-09-27 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_event_contact_event_end_time_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaydetails',
            name='event',
            field=models.OneToOneField(blank=True, limit_choices_to={'event_type': 'BIRTHDAY'}, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='collegefestdetails',
            name='event',
            field=models.OneToOneField(blank=True, limit_choices_to={'event_type': 'FEST'}, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='corporatedetails',
            name='event',
            field=models.OneToOneField(blank=True, limit_choices_to={'event_type': 'CONFERENCE'}, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='weddingdetails',
            name='event',
            field=models.OneToOneField(blank=True, limit_choices_to={'event_type': 'WEDDING'}, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
    ]
