# Generated by Django 5.1.1 on 2024-09-27 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_alter_birthdaydetails_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaydetails',
            name='event',
            field=models.OneToOneField(blank=True, limit_choices_to={'event_type': 'BIRTHDAY'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='collegefestdetails',
            name='event',
            field=models.OneToOneField(blank=True, limit_choices_to={'event_type': 'FEST'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='corporatedetails',
            name='event',
            field=models.OneToOneField(blank=True, limit_choices_to={'event_type': 'CONFERENCE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='weddingdetails',
            name='event',
            field=models.OneToOneField(blank=True, limit_choices_to={'event_type': 'WEDDING'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
    ]
