# Generated by Django 5.1.1 on 2024-09-27 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_alter_birthdaydetails_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingdetails',
            name='event',
            field=models.ForeignKey(blank=True, limit_choices_to={'event_type': 'WEDDING'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
    ]
