# Generated by Django 5.1.1 on 2024-09-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_alter_weddingdetails_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaydetails',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='collegefestdetails',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='corporatedetails',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='weddingdetails',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
    ]
