# Generated by Django 5.1.1 on 2024-09-27 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0009_alter_birthdaydetails_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaydetails',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='collegefestdetails',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='corporatedetails',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
    ]
