# Generated by Django 5.1.1 on 2024-09-27 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0015_tasks_assigned_by_alter_tasks_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
    ]
