# Generated by Django 5.1.1 on 2024-09-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0016_tasks_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
