# Generated by Django 5.1.1 on 2024-09-28 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Event', '0018_alter_event_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('conference', 'Conference'), ('fest', 'College Fest'), ('corporate', 'Corporate Event'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.organiser'),
        ),
    ]
