# Generated by Django 5.1.1 on 2024-09-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0019_alter_event_event_type_alter_event_organiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('vendor_type', models.CharField(choices=[('Caterer', 'Caterer'), ('Florist', 'Florist'), ('DJ', 'DJ'), ('Photographer', 'Photographer'), ('Decorator', 'Decorator'), ('Other', 'Other')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
