# Generated by Django 5.1.1 on 2024-09-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0021_tasks_vendor_alter_vendor_vendor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='actual_bg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='expected_bg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
